# Generated by Django 3.2.9 on 2021-12-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('Account_no', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('IFSC_code', models.CharField(max_length=1000)),
                ('Branch', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=1000)),
                ('Current_amount', models.IntegerField()),
                ('Investor_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('Website_link', models.CharField(max_length=1000)),
                ('CEO', models.CharField(max_length=1000)),
                ('Revenue', models.IntegerField()),
                ('Parent_org', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Company_category',
            fields=[
                ('category', models.CharField(max_length=1000)),
                ('Compnay_name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('quantity', models.IntegerField()),
                ('PL', models.FloatField()),
                ('Invested_Amt', models.FloatField()),
                ('Purchased_Value', models.FloatField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Stock_ISN', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=1000)),
                ('LastName', models.CharField(max_length=1000)),
                ('No_of_Investments', models.IntegerField()),
                ('Contact_no', models.CharField(max_length=13)),
                ('Pan_card_no', models.CharField(max_length=1000)),
                ('Address_line1', models.CharField(max_length=1000)),
                ('Address_line2', models.CharField(max_length=1000)),
                ('State', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('District', models.CharField(max_length=1000)),
                ('Pin_code', models.IntegerField()),
                ('User_login_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_name', models.CharField(max_length=1000)),
                ('ISIN', models.IntegerField(primary_key=True, serialize=False)),
                ('volume', models.IntegerField()),
                ('Avg_traded_price', models.FloatField()),
                ('lower_ckt', models.FloatField()),
                ('upper_ckt', models.FloatField()),
                ('value', models.FloatField()),
                ('growth', models.FloatField()),
                ('company_name', models.IntegerField()),
            ],
        ),
    ]
