# Generated by Django 4.0 on 2021-12-12 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='longBusinessSummary',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000),
            preserve_default=False,
        ),
    ]
