# Generated by Django 3.2.9 on 2022-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0013_alter_investor_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='Contact_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
